# Generated by Django 4.2 on 2023-04-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="fechaFinalizacion",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="curso",
            name="fechaInicio",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
