# Generated by Django 4.2 on 2023-04-08 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100)),
                ('altura', models.IntegerField()),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'domicilio',
                'verbose_name_plural': 'domicilios',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=16)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Estudiante')),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.domicilio')),
            ],
            options={
                'verbose_name': 'estudiante',
                'verbose_name_plural': 'estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tutor', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Curso')),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ManyToManyField(to='cursos.categoria')),
                ('estudiante', models.ManyToManyField(to='cursos.estudiante')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
            },
        ),
    ]
