# Generated by Django 4.2 on 2023-04-09 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='imagen',
        ),
    ]
