# Generated by Django 4.2 on 2023-04-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0002_alter_curso_fechafinalizacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="fechaFinalizacion",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="curso",
            name="fechaInicio",
            field=models.DateTimeField(),
        ),
    ]
