# Generated by Django 4.2 on 2023-04-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_curso_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='estudiante',
            field=models.ManyToManyField(to='cursos.estudiante'),
        ),
    ]
