# Generated by Django 4.2 on 2023-04-09 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_curso_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='domicilio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cursos.domicilio'),
        ),
    ]
