# Generated by Django 4.2 on 2023-04-09 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_alter_estudiante_domicilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='domicilio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.domicilio'),
        ),
    ]
