# Generated by Django 4.2 on 2023-04-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("correo_electronico", models.EmailField(max_length=254)),
                ("telefono", models.IntegerField()),
                ("pais", models.CharField(max_length=30)),
                ("fecha", models.DateField()),
            ],
        ),
    ]
