# Generated by Django 4.2 on 2023-04-09 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crud_api", "0002_estudiante"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estudiante",
            name="fecha",
        ),
    ]
